name: test-fleek-iterative-deploy

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: run deploy test
              env:
                  FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
                  FLEEK_SITE_ID: ${{ secrets.FLEEK_SITE_ID }}
                  FLEEK_TEAM_ID: ${{ secrets.FLEEK_TEAM_ID }}
              run: |
                  npm ci
                  npx fleek-iterative-deploy
